### ISSUE TITLE
Ubuntu build version name not changing

### ISSUE THREAD

**Issue by TheUbuntuGuy** [clementine-player/Buildbot#4]
Since the recent changes, the version for the builds has stayed at `clementine_1.2.3-1280-g10860b7` and the buildbot is replacing builds instead of adding new ones.

**Comment by TheUbuntuGuy** [comment]
Sorry about the apparent vagueness when submitting this, I was on mobile. The issue is not resolved with your change. What I meant was that the file named `clementine_1.2.3-1280-g10860b7` is being replaced with the output of the latest build, however every build is named the same, the version number and git hash do not change. It's overwriting the file rather than adding a new one numbered 1281, 1282, etc. The version in Clementine's about box is also still the same too, and when installing the .deb package, you have to 'reinstall' rather than 'update' because the versions are the same.

**Comment by davidsansome** [comment]
That seems to have fixed it (tested with trusty-64)...

These were actually 2 separate problems - thanks for following up and making sure I fixed both.  The builds take ages so most of the time I'll start all the builders before going to sleep, and then not check again for another couple of days.
